name: bearer

on: push

jobs:
  bearer:
    name: Bearer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bearer
        run: |
          curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh

      - name: Run Bearer
        run: |
          ./bin/bearer scan ./